### ISSUE TITLE
README.MD for each design pattern

### ISSUE THREAD

**Issue by egeldenhuys** [RagingGrim/DesignPatterns#4]
Suggestion:
Add a README.MD to root of each design pattern containing a brief overview such as participants and intent etc. Also include a UML diagram. 
This repo can then be used as a quick reference guide. I have already started Implementing this in my fork.

Is this in line with your vision for the repo?

**Comment by CDuPlooy** [comment]
I was cautious about adding uml diagrams to the repositories because of their size.  In retrospect I don't think size should be an issue.  

Are you creating the uml diagrams yourself or using examples which already exist? 

I think it's a good idea. The coming weekend ill start adding a few more patterns and standerdise what we've already done.

**Comment by egeldenhuys** [comment]
I am using [Dia](http://dia-installer.de/) to recreate the examples we are given in class. See [template-method.png](https://github.com/egeldenhuys/DesignPatterns/blob/9363ecd61c658f87b927987e1d4f9e3047c92171/resources/template-method.png) (14.3 KB) for example.
